class pin:
    IN: int
    OUT: int
    PULL_UP: int
    def __init__(self, id, mode: int = ..., pull: int = ...)-> None: ...
    def value(self, v: int = ...)-> int: ...

class I2C:
    def __init__(self, id: int, scl=None, sda=None, freq: int = ...): ...
    def scan(self)-> list: ...
    def readfrom(self, addr: int, nbytes: int)-> bytes: ...
    def writeto(self, addr: int, buf) -> int: ...

class ADC:
    def __init__(self, pin) -> None: ...
    def read_u16(self) -> int: ...

def reset() -> None: ...
def freq(val: int = ...) -> int: ...